# https://andrewtarry.com/posts/terraform-eks-alb-setup/
# ingress configuration for a simple load balancer
# This will create an ALB thats connected to your ingress. 
# The annotations are documented in the ALB Load Balancer Controller so 
# you can configure certifications, internet facing load balancers and detailed routing rules.
# https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/
# https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/spec/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-lb
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/load-balancer-name: alb-name
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: none
      port:
        number: 80
